# .github/actions/send-junit-to-api/action.yml
name: Send JUNIT XML Files to Evergreen API
description: Sends JUNIT XML files to the Evergreen API.

on:
  workflow_call:
    inputs:
      subproject:
        required: false
        type: string
        description: 'Sub project name'

runs:
  using: "composite"
  steps:
    - name: Send JUNIT XML Files to Evergreen API
      continue-on-error: true
      shell: bash
      run: |
        echo "Workflow Run ID: ${{ github.run_id }}"

        # Define the base URL
        if [ "${{ contains(runner.labels, 'self-hosted') }}" == "true" ]; then
          base_url="http://evergreen.ihmc.us"
        else
          base_url="https://evergreen.ihmc.us"
        fi

        echo "Using base URL: $base_url"

        # Check if the subproject input is provided
        if [ -n "${{ inputs.subproject }}" ]; then
          dir="repository-group/${{ github.event.repository.name }}/${{ inputs.subproject }}/src/test/build/test-results/test/"
        else
          dir="repository-group/${{ github.event.repository.name }}/src/test/build/test-results/test/"
        fi
        
        if [ -d "$dir" ]; then
          echo "Directory exists, changing directory to $dir"
          cd "$dir"
        
          for file in TEST-*.xml; do
            if [ -f "$file" ]; then
              echo "Sending $file to API"
              curl -L -X POST \
                -H "WorkflowRunID: ${{ github.run_id }}" \
                -F "file=@$file" \
                "$base_url/api/junitupload.php"
            else
              echo "No XML files found matching TEST-*.xml"
            fi
          done
          
          curl -L -X GET "$base_url/api/update_workflow.php"
        else
          echo "Directory $dir does not exist, skipping."
        fi
