# .github/actions/send-junit-to-api/action.yml
name: Send JUNIT XML Files to Evergreen API
description: Sends JUNIT XML files to the Evergreen API.

on:
  workflow_call:
    inputs:
      subproject:
        required: false
        type: string
        description: 'Sub project name'

runs:
  using: "composite"
  steps:
    - name: Send JUNIT XML Files to Evergreen API
      shell: bash
      run: |
        echo "Workflow Run ID: ${{ github.run_id }}"

        # Check if the subproject input is provided
        if [ -n "${{ inputs.subproject }}" ]; then
          dir="repository-group/${{ github.event.repository.name }}/${{ inputs.subproject }}/src/test/build/test-results/test/"
        else
          dir="repository-group/${{ github.event.repository.name }}/src/test/build/test-results/test/"
        fi
        
        if [ -d "$dir" ]; then
          echo "Directory exists, changing directory to $dir"
          cd "$dir"
        
          for file in TEST-*.xml; do
            if [ -f "$file" ]; then
              echo "Sending $file to API"
              curl -X POST \
                -H "WorkflowRunID: ${{ github.run_id }}" \
                -F "file=@$file" \
                http://evergreen.ihmc.us/api/junitupload.php
            else
              echo "No XML files found matching TEST-*.xml"
            fi
          done
        else
          echo "Directory $dir does not exist, skipping."
        fi
