# .github/actions/force-update-evergreen/action.yml
name: Force update evergreen repo
description: Calls evergreen force update api

on:
  workflow_call:    

runs:
  using: "composite"
  steps:
    - name: Calls evergreen force update api
      continue-on-error: true
      shell: bash
      run: |
        if [ "${{ contains(runner.labels, 'self-hosted') }}" == "true" ]; then
          base_url="http://evergreen.ihmc.us"
        else
          base_url="https://evergreen.ihmc.us"
        fi
        echo "Calling force update - $base_url/api/update_workflow.php"
        curl -L -X GET \
              -H "REPONAME: ${{ github.event.repository.name }}" \
              "$base_url/api/update_workflow.php"
