name: _gradle_base

on:
  workflow_call:
    inputs:
      subproject:
        description: 'Subproject'
        required: false
        type: string
      test-category:
        description: 'Test category'
        required: false
        type: string
        default: 'fast'
      setup-javafx-headless:
        description: 'Setup JavaFX headless'
        required: false
        type: boolean
        default: false

runs:
  using: composite
  steps:
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-package: 'jdk'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        id: setup-gradle
        with:
          gradle-version: 8.9

      - name: Set up JavaFX deps
        shell: bash
        if: ${{ inputs.setup-javafx-headless }}
        run: |
          sudo apt-get update -y && sudo apt-get install -y libxxf86vm1 libgl1-mesa-glx

      - name: Set up Virtual Display (for Linux)
        shell: bash
        if: ${{ inputs.setup-javafx-headless }} && ( runner.os == 'Linux' )
        run: |
          Xvfb ${{env.DISPLAY}} ${{env.XVFB_PARMS}} &

      - name: Gradle test - ${{ inputs.test-category }}
        shell: bash
        run: |
          if [[ -n "${{ inputs.subproject }}" ]]; then
            cd "${{ inputs.subproject }}"
          fi
          gradle test -Pcategory=${{ inputs.test-category }} --info --no-daemon -PrunningOnCIServer=true
          
      - name: Publish JUnit test report - ${{ inputs.test-category }}
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          detailed_summary: true
